name: ESLint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  eslint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@9.6.0

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.yaml
          --ext .js,.jsx,.ts,.tsx
        continue-on-error: true
