export enum WebhookErrorCode {
  missingAPIKeyHeader = 'missingAPIKeyHeader',
  forbidden = 'forbidden',
  developerAccountNotActive = 'developerAccountNotActive',
  resourceNotFound = 'resourceNotFound',
  invalidValueWebhookURLRequired = 'invalidValueWebhookURLRequired',
  invalidValueWebhookURLCannotBeBlank = 'invalidValueWebhookURLCannotBeBlank',
  invalidValueWebhookURLTooLong = 'invalidValueWebhookURLTooLong',
  invalidWebhookURLMissingHTTPS = 'invalidWebhookURLMissingHTTPS',
  invalidWebhookURLNoResponse = 'invalidWebhookURLNoResponse',
  invalidEventSchemaVersionRequired = 'invalidEventSchemaVersionRequired',
  invalidEventSchemaVersion = 'invalidEventSchemaVersion',
  invalidValueEventIdsRequired = 'invalidValueEventIdsRequired',
  invalidValueEventIdsCannotBeBlank = 'invalidValueEventIdsCannotBeBlank',
  invalidValueEventIds = 'invalidValueEventIds',
  invalidValueReferenceIdTooLong = 'invalidValueReferenceIdTooLong',
  invalidSubscriptionId = 'invalidSubscriptionId',
  invalidWebhookUrlBadFormat = 'invalidWebhookUrlBadFormat',
  invalidWebhookUrlError = 'invalidWebhookUrlError',
  subscriptionStatusNotValid = 'subscriptionStatusNotValid',
}
